# Base configs
baseurl: ""
url: "http://andrewblair.ca"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-XXXXXXXX"

# UI configs push
title: "Photography by Andrew Blair"
subtitle: "I have vision."
author: "Andrew Blair"
bio: "For the past 13 years, Sir Andrew Blair, loyal citizen of Her Majesty the Queen, has been capturing some of the hottest imagery around. If you're cool, you can hire him."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/andrewblair"
  instagram: "https://www.instagram.com/axbotv"
  tumblr: "http://sickxmachine.tumblr.com"
  