# Base configs
baseurl: ""
url: "http://andrewblair.ca"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-XXXXXXXX"

# UI configs push
title: "Photography by Andrew Blair"
subtitle: "trial and error"
author: "Andrew Blair"
bio: "I am currently residing in Southern Ontario after 30 years of braving Northern Ontario where I've been taking photos since 2004. I enjoy capturing the interesting things and people around me. Feel free to check out my work, and if you'd like to work with me, get in touch!"

social_urls:
  facebook: "https://www.facebook.com/andrewblair"
  instagram: "https://www.instagram.com/axbotv"
  tumblr: "http://sickxmachine.tumblr.com"
  
